#yml 文件  与  properties 均为配置文件    yml文件的值   一定要有个空格   注意层级关系
#driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /springboot1

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zy1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000ms
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
mybatis:
  type-aliases-package: com.example.springboot1.pojo
  mapper-locations: classpath:/mapper/*.xml